# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment CustomResourceDefinitions
name: app-deployment-crd
# Correct version will be added by "make helm-package" from VERSION
version: 2.6.0
annotations:
  revision: "a55c594"
  created: "2026-01-27T04:26:32Z"
appVersion: 2.6.0
