# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment CustomResourceDefinitions
name: app-deployment-crd
# Correct version will be added by "make helm-package" from VERSION
version: 2.6.1
annotations:
  revision: "77d030b"
  created: "2026-02-26T06:20:45Z"
appVersion: 2.6.1
