# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment Manager
name: app-deployment-manager
# Correct version will be added by "make helm-package" from VERSION
version: 2.5.6-dev
annotations:
  revision: "074ee3e"
  created: "2025-11-03T16:19:33Z"
appVersion: 2.5.6-dev-074ee3e
