# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment Manager
name: app-deployment-manager
# Correct version will be added by "make helm-package" from VERSION
version: 2.5.8
annotations:
  revision: "2177ba2"
  created: "2025-11-25T06:23:24Z"
appVersion: 2.5.8
