# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment Manager
name: app-deployment-manager
# Correct version will be added by "make helm-package" from VERSION
version: 2.6.1-dev
annotations:
  revision: "bafd028"
  created: "2026-02-24T10:46:37Z"
appVersion: 2.6.1-dev-bafd028
