# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-interconnect-manager
description: A Helm chart for Kubernetes
type: application
version: 0.3.2-dev
appVersion: "0.3.2-dev-074ee3e"
annotations:
  revision: "074ee3e"
  created: "2025-11-03T16:21:43Z"
