# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-interconnect-manager
description: A Helm chart for Kubernetes
type: application
version: 0.3.2
appVersion: "0.3.2"
annotations:
  revision: "2177ba2"
  created: "2025-11-25T06:22:58Z"
